QUOTES1 = [
    "In the midst of chaos, there is also opportunity. — Sun Tzu",
    "Waste no more time arguing about what a good man should be. Be one. — Marcus Aurelius",
    "He who conquers himself is the mightiest warrior. — Confucius",
    "The unexamined life is not worth living. — Socrates",
    "Luck is what happens when preparation meets opportunity. — Seneca",
    "Be kind, for everyone you meet is fighting a harder battle. — Plato",
    "Courage, above all things, is the first quality of a warrior. — Carl von Clausewitz",
    "Man suffers more in imagination than in reality. — Seneca",
    "Knowing yourself is the beginning of all wisdom. — Aristotle",
    "Do not pray for an easy life, pray for the strength to endure a difficult one. — Bruce Lee",
    "To know your Enemy, you must become your Enemy. — Sun Tzu",
    "The best revenge is not to be like your enemy. — Marcus Aurelius",
    "Wealth consists not in having great possessions, but in having few wants. — Epictetus",
    "It is not death that a man should fear, but he should fear never beginning to live. — Marcus Aurelius",
    "Appear weak when you are strong, and strong when you are weak. — Sun Tzu",
    "Fortune favors the bold. — Latin Proverb",
    "He who opens a school door, closes a prison. — Victor Hugo",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle",
    "Even death is not to be feared by one who has lived wisely. — Buddha",
    "Do what you can, with what you have, where you are. — Theodore Roosevelt",
    "Opportunities multiply as they are seized. — Sun Tzu",
    "The brave man is not he who does not feel afraid, but he who conquers that fear. — Nelson Mandela",
    "A room without books is like a body without a soul. — Cicero",
    "Throw me to the wolves and I will return leading the pack. — Seneca",
    "Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat. — Sun Tzu",
    "The man who moves a mountain begins by carrying away small stones. — Confucius",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. — Mahatma Gandhi",
    "First say to yourself what you would be; and then do what you have to do. — Epictetus",
    "Victory is reserved for those who are willing to pay its price. — Sun Tzu",
    "The soul becomes dyed with the color of its thoughts. — Marcus Aurelius",
    "Knowledge without justice ought to be called cunning rather than wisdom. — Plato",
    "What we achieve inwardly will change outer reality. — Plutarch",
    "No man has a good enough memory to be a successful liar. — Abraham Lincoln",
    "Poverty is the parent of revolution and crime. — Aristotle",
    "Cowards die many times before their deaths; the valiant never taste of death but once. — Julius Caesar",
    "The more you sweat in peace, the less you bleed in war. — Norman Schwarzkopf",
    "We are more often frightened than hurt; and we suffer more in imagination than in reality. — Seneca",
    "The greatest victory is to conquer yourself. — Aristotle",
    "Wars begin in the minds of men. — UNESCO preamble",
    "If you are far from the enemy, make him believe you are near. — Sun Tzu",
    "He who has a why to live can bear almost any how. — Friedrich Nietzsche",
    "Discipline is the soul of an army. — George Washington",
    "Happiness depends upon ourselves. — Aristotle",
    "Better to fight for something than live for nothing. — George S. Patton",
    "An ounce of practice is worth more than tons of preaching. — Mahatma Gandhi",
    "The way is not in the sky. The way is in the heart. — Buddha",
    "History is written by the victors. — Winston Churchill",
    "The supreme art of war is to subdue the enemy without fighting. — Sun Tzu",
    "Liberty means responsibility. That is why most men dread it. — George Bernard Shaw",
    "A man who dares to waste one hour of time has not discovered the value of life. — Charles Darwin",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. — Ralph Waldo Emerson",
    "Live life as though nobody is watching, and express yourself as though everyone is listening. — Nelson Mandela",
    "Power tends to corrupt, and absolute power corrupts absolutely. — Lord Acton",
    "He who is not courageous enough to take risks will accomplish nothing in life. — Muhammad Ali",
    "Glory is fleeting, but obscurity is forever. — Napoleon Bonaparte",
    "Be as you wish to seem. — Socrates",
    "No man is free who is not a master of himself. — Epictetus",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. — Buddha",
    "There is nothing impossible to him who will try. — Alexander the Great",
    "Perseverance, secret of all triumphs. — Victor Hugo",
    "Freedom is nothing else but a chance to be better. — Albert Camus",
    "We must all suffer one of two things: the pain of discipline or the pain of regret. — Jim Rohn",
    "Bravery is the solution to regret. — Robin Sharma",
    "The future depends on what you do today. — Mahatma Gandhi",
    "Fall seven times and stand up eight. — Japanese Proverb",
    "The wise man does at once what the fool does finally. — Niccolò Machiavelli",
    "It always seems impossible until it’s done. — Nelson Mandela",
    "Silence is a true friend who never betrays. — Confucius",
    "Our life is what our thoughts make it. — Marcus Aurelius",
    "Do not wait to strike till the iron is hot, but make it hot by striking. — William Butler Yeats",
    "Action is the foundational key to all success. — Pablo Picasso",
    "You must be the change you wish to see in the world. — Mahatma Gandhi",
    "A hero is no braver than an ordinary man, but he is brave five minutes longer. — Ralph Waldo Emerson",
    "The harder the conflict, the greater the triumph. — George Washington",
    "Do not go gentle into that good night. — Dylan Thomas",
    "It is not length of life, but depth of life. — Ralph Waldo Emerson",
    "We are masters of the unsaid words, but slaves of those we let slip out. — Winston Churchill",
    "Victory belongs to the most persevering. — Napoleon Bonaparte",
    "A leader is one who knows the way, goes the way, and shows the way. — John C. Maxwell",
    "Do not let what you cannot do interfere with what you can do. — John Wooden",
    "Experience is the teacher of all things. — Julius Caesar",
    "An army of sheep led by a lion is better than an army of lions led by a sheep. — Alexander the Great",
    "Strength does not come from physical capacity. It comes from an indomitable will. — Mahatma Gandhi",
    "Character is destiny. — Heraclitus",
    "A warrior is worthless unless he rises above others and stands strong in the midst of a storm. — Yamamoto Tsunetomo",
    "There is nothing more powerful than an idea whose time has come. — Victor Hugo",
    "To improve is to change; to be perfect is to change often. — Winston Churchill",
    "Energy and persistence conquer all things. — Benjamin Franklin",
    "Success is how high you bounce when you hit bottom. — George S. Patton",
    "What we think, we become. — Buddha",
    "Great spirits have always encountered violent opposition from mediocre minds. — Albert Einstein",
    "You can’t cross the sea merely by standing and staring at the water. — Rabindranath Tagore",
    "He who fears he will suffer, already suffers because he fears. — Michel de Montaigne",
    "The true measure of a man is how he treats someone who can do him absolutely no good. — Samuel Johnson",
    "Destiny is not a matter of chance; it is a matter of choice. — William Jennings Bryan",
    "Do not count the days, make the days count. — Muhammad Ali",
    "Time is the most valuable thing a man can spend. — Theophrastus",
    "Great deeds are usually wrought at great risks. — Herodotus",
    "The weak can never forgive. Forgiveness is the attribute of the strong. — Mahatma Gandhi"
]


QUOTES2 = [
    "He who is not courageous enough to take risks will accomplish nothing in life. — Muhammad Ali",
    "Do not pray for an easy life, pray for the strength to endure a difficult one. — Bruce Lee",
    "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change. — Charles Darwin",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela",
    "Discipline is the bridge between goals and accomplishment. — Jim Rohn",
    "He who controls others may be powerful, but he who has mastered himself is mightier still. — Lao Tzu",
    "The obstacle on the path becomes the path. Never forget, within every obstacle is an opportunity to improve our condition. — Seneca",
    "The superior man is modest in his speech but exceeds in his actions. — Confucius",
    "Happiness is not something ready-made. It comes from your own actions. — Dalai Lama",
    "In war, the way is to avoid what is strong and to strike at what is weak. — Sun Tzu",
    "Man conquers the world by conquering himself. — Zeno of Citium",
    "You have power over your mind — not outside events. Realize this, and you will find strength. — Marcus Aurelius",
    "The wise man bridges the gap by laying out the path. — Confucius",
    "Success is stumbling from failure to failure with no loss of enthusiasm. — Winston Churchill",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. — Jane Goodall",
    "The art of war teaches us to rely not on the likelihood of the enemy's not coming, but on our own readiness. — Sun Tzu",
    "He who is brave is free. — Seneca",
    "If you want to live a happy life, tie it to a goal, not to people or things. — Albert Einstein",
    "Courage is not the absence of fear — it’s inspiring others to move beyond it. — Ronald Reagan",
    "A journey of a thousand miles begins with a single step. — Lao Tzu",
    "Fortune and love favor the brave. — Ovid",
    "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
    "Do not let what you cannot do interfere with what you can do. — John Wooden",
    "A wise man does not grieve for things he has not, but rejoices for those he has. — Epictetus",
    "Knowledge is power. — Francis Bacon",
    "The secret of change is to focus all of your energy, not on fighting the old, but on building the new. — Socrates",
    "Experience is the teacher of all things. — Julius Caesar",
    "Fortune favors the prepared mind. — Louis Pasteur",
    "To know oneself is the beginning of all wisdom. — Aristotle",
    "A leader is one who knows the way, goes the way, and shows the way. — John C. Maxwell",
    "No act of kindness, no matter how small, is ever wasted. — Aesop",
    "Strength does not come from physical capacity. It comes from an indomitable will. — Mahatma Gandhi",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people. — Eleanor Roosevelt",
    "Do what you can, with what you have, where you are. — Theodore Roosevelt",
    "Time is free, but it's priceless. You can’t own it, but you can use it. — Harvey Mackay",
    "The way to gain a good reputation is to endeavor to be what you desire to appear. — Socrates",
    "He who learns but does not think, is lost! He who thinks but does not learn is in great danger. — Confucius",
    "An investment in knowledge pays the best interest. — Benjamin Franklin",
    "He who is not courageous enough to take risks will accomplish nothing in life. — Muhammad Ali",
    "Do not wait to strike till the iron is hot; but make it hot by striking. — William Butler Yeats",
    "The mind is everything. What you think you become. — Buddha",
    "Education is the most powerful weapon which you can use to change the world. — Nelson Mandela",
    "Fortune favors the bold. — Terence",
    "The more I read, the more I acquire, the more certain I am that I know nothing. — Voltaire",
    "It is not in the stars to hold our destiny but in ourselves. — William Shakespeare",
    "He who opens a school door, closes a prison. — Victor Hugo",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. — Winston Churchill",
    "A good head and a good heart are always a formidable combination. — Nelson Mandela",
    "Knowing others is intelligence; knowing yourself is true wisdom. — Lao Tzu",
    "Strength and growth come only through continuous effort and struggle. — Napoleon Hill",
    "In the middle of difficulty lies opportunity. — Albert Einstein",
    "The superior man acts before he speaks, and afterwards speaks according to his action. — Confucius",
    "Opportunities don’t happen. You create them. — Chris Grosser",
    "Fortune sides with him who dares. — Virgil",
    "A warrior does not give up what he loves, he finds the love in what he does. — Dan Millman",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. — Ralph Waldo Emerson",
    "Character is destiny. — Heraclitus",
    "He who fears he will suffer, already suffers because he fears. — Michel de Montaigne",
    "No man is free who is not a master of himself. — Epictetus",
    "Happiness depends upon ourselves. — Aristotle",
    "The greatest mistake you can make in life is to be continually fearing that you will make one. — Elbert Hubbard",
    "Fall seven times and stand up eight. — Japanese Proverb",
    "The best way to predict the future is to create it. — Peter Drucker",
    "Do not pray for an easy life, pray for the strength to endure a difficult one. — Bruce Lee",
    "Do not count the days, make the days count. — Muhammad Ali",
    "Wisdom begins in wonder. — Socrates",
    "The only true wisdom is in knowing you know nothing. — Socrates",
    "A man who dares to waste one hour of time has not discovered the value of life. — Charles Darwin",
    "The mind is everything. What you think you become. — Buddha",
    "Action is the foundational key to all success. — Pablo Picasso",
    "In war, there is no substitute for victory. — Douglas MacArthur",
    "The unexamined life is not worth living. — Socrates",
    "The superior man is modest in his speech, but exceeds in his actions. — Confucius",
    "Happiness is not something ready-made. It comes from your own actions. — Dalai Lama",
    "What we achieve inwardly will change outer reality. — Plutarch",
    "Courage is resistance to fear, mastery of fear — not absence of fear. — Mark Twain",
    "He who opens a school door, closes a prison. — Victor Hugo",
    "Victory belongs to the most persevering. — Napoleon Bonaparte",
    "Do not let what you cannot do interfere with what you can do. — John Wooden",
    "An army of sheep led by a lion is better than an army of lions led by a sheep. — Alexander the Great",
    "Strength does not come from physical capacity. It comes from an indomitable will. — Mahatma Gandhi",
    "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
    "Great spirits have always encountered violent opposition from mediocre minds. — Albert Einstein",
    "Power tends to corrupt, and absolute power corrupts absolutely. — Lord Acton",
    "The obstacle on the path becomes the path. — Seneca",
    "A leader is one who knows the way, goes the way, and shows the way. — John C. Maxwell",
    "The true measure of a man is how he treats someone who can do him absolutely no good. — Samuel Johnson",
    "The greatest victory is to conquer yourself. — Aristotle",
    "Experience is the teacher of all things. — Julius Caesar",
    "An ounce of practice is worth more than tons of preaching. — Mahatma Gandhi",
    "Do what you can, with what you have, where you are. — Theodore Roosevelt",
    "You have power over your mind — not outside events. Realize this, and you will find strength. — Marcus Aurelius",
    "To know oneself is the beginning of all wisdom. — Aristotle",
    "The harder the conflict, the greater the triumph. — George Washington",
    "He who controls others may be powerful, but he who has mastered himself is mightier still. — Lao Tzu",
    "No act of kindness, no matter how small, is ever wasted. — Aesop",
    "Education is the most powerful weapon which you can use to change the world. — Nelson Mandela",
    "Great deeds are usually wrought at great risks. — Herodotus",
    "If you want to live a happy life, tie it to a goal, not to people or things. — Albert Einstein"
]

QUOTES3 = [
    "Do not be afraid to give up the good to go for the great. — John D. Rockefeller",
    "The best revenge is massive success. — Frank Sinatra",
    "If you want peace, prepare for war. — Vegetius",
    "He who is brave is free. — Seneca",
    "Knowing yourself is the beginning of all wisdom. — Aristotle",
    "A goal without a plan is just a wish. — Antoine de Saint-Exupéry",
    "The greatest wealth is to live content with little. — Plato",
    "Strength does not come from winning. Your struggles develop your strengths. — Arnold Schwarzenegger",
    "The best way to find yourself is to lose yourself in the service of others. — Mahatma Gandhi",
    "He who learns but does not think, is lost! He who thinks but does not learn is in great danger. — Confucius",
    "It is not what we do, but also what we do not do, for which we are accountable. — Molière",
    "Time is the most valuable thing a man can spend. — Theophrastus",
    "The supreme art of war is to subdue the enemy without fighting. — Sun Tzu",
    "Do not go gentle into that good night. — Dylan Thomas",
    "Fall seven times and stand up eight. — Japanese Proverb",
    "Discipline is the bridge between goals and accomplishment. — Jim Rohn",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle",
    "A room without books is like a body without a soul. — Cicero",
    "The obstacle is the way. — Marcus Aurelius",
    "No man is free who is not a master of himself. — Epictetus",
    "The only true wisdom is in knowing you know nothing. — Socrates",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. — Winston Churchill",
    "Great spirits have always encountered violent opposition from mediocre minds. — Albert Einstein",
    "Power tends to corrupt, and absolute power corrupts absolutely. — Lord Acton",
    "Courage is not the absence of fear — it’s mastery of fear. — Mark Twain",
    "Experience is the teacher of all things. — Julius Caesar",
    "Victory belongs to the most persevering. — Napoleon Bonaparte",
    "He who opens a school door, closes a prison. — Victor Hugo",
    "The harder the conflict, the greater the triumph. — George Washington",
    "Do not let what you cannot do interfere with what you can do. — John Wooden",
    "Knowing others is intelligence; knowing yourself is true wisdom. — Lao Tzu",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela",
    "Opportunities don't happen. You create them. — Chris Grosser",
    "Happiness is not something ready-made. It comes from your own actions. — Dalai Lama",
    "Do what you can, with what you have, where you are. — Theodore Roosevelt",
    "He who fears he will suffer, already suffers because he fears. — Michel de Montaigne",
    "Strength and growth come only through continuous effort and struggle. — Napoleon Hill",
    "An army of sheep led by a lion is better than an army of lions led by a sheep. — Alexander the Great",
    "The mind is everything. What you think you become. — Buddha",
    "Education is the most powerful weapon which you can use to change the world. — Nelson Mandela",
    "A warrior does not give up what he loves, he finds the love in what he does. — Dan Millman",
    "The superior man is modest in his speech, but exceeds in his actions. — Confucius",
    "He who controls others may be powerful, but he who has mastered himself is mightier still. — Lao Tzu",
    "Do not count the days, make the days count. — Muhammad Ali",
    "Character is destiny. — Heraclitus",
    "Great deeds are usually wrought at great risks. — Herodotus",
    "Time is free, but it's priceless. You can’t own it, but you can use it. — Harvey Mackay",
    "The mind is everything. What you think you become. — Buddha",
    "Action is the foundational key to all success. — Pablo Picasso",
    "In war, there is no substitute for victory. — Douglas MacArthur",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. — Buddha",
    "The superior man acts before he speaks, and afterwards speaks according to his action. — Confucius",
    "Fortune favors the bold. — Terence",
    "He who is not courageous enough to take risks will accomplish nothing in life. — Muhammad Ali",
    "A good head and a good heart are always a formidable combination. — Nelson Mandela",
    "The true measure of a man is how he treats someone who can do him absolutely no good. — Samuel Johnson",
    "No act of kindness, no matter how small, is ever wasted. — Aesop",
    "Knowledge is power. — Francis Bacon",
    "The best way to predict the future is to create it. — Peter Drucker",
    "Do not be afraid to give up the good to go for the great. — John D. Rockefeller",
    "The more I read, the more I acquire, the more certain I am that I know nothing. — Voltaire",
    "It is not in the stars to hold our destiny but in ourselves. — William Shakespeare",
    "Strength does not come from physical capacity. It comes from an indomitable will. — Mahatma Gandhi",
    "A leader is one who knows the way, goes the way, and shows the way. — John C. Maxwell",
    "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people. — Eleanor Roosevelt",
    "The obstacle on the path becomes the path. — Seneca",
    "A journey of a thousand miles begins with a single step. — Lao Tzu",
    "Fall seven times and stand up eight. — Japanese Proverb",
    "Do not wait to strike till the iron is hot; but make it hot by striking. — William Butler Yeats",
    "Wisdom begins in wonder. — Socrates",
    "The superior man is modest in his speech but exceeds in his actions. — Confucius",
    "Fortune favors the prepared mind. — Louis Pasteur",
    "Success is stumbling from failure to failure with no loss of enthusiasm. — Winston Churchill",
    "Happiness depends upon ourselves. — Aristotle",
    "He who opens a school door, closes a prison. — Victor Hugo",
    "The only true wisdom is in knowing you know nothing. — Socrates",
    "The greatest mistake you can make in life is to be continually fearing that you will make one. — Elbert Hubbard",
    "Knowledge without justice ought to be called cunning rather than wisdom. — Plato",
    "The best revenge is not to be like your enemy. — Marcus Aurelius",
    "Even death is not to be feared by one who has lived wisely. — Buddha",
    "Appear weak when you are strong, and strong when you are weak. — Sun Tzu",
    "Opportunities multiply as they are seized. — Sun Tzu",
    "Happiness is the highest good. — Aristotle",
    "Man conquers the world by conquering himself. — Zeno of Citium",
    "Do not let what you cannot do interfere with what you can do. — John Wooden",
    "Energy and persistence conquer all things. — Benjamin Franklin",
    "You must be the change you wish to see in the world. — Mahatma Gandhi",
    "Knowledge is power. — Francis Bacon",
    "What we achieve inwardly will change outer reality. — Plutarch",
    "A hero is no braver than an ordinary man, but he is brave five minutes longer. — Ralph Waldo Emerson",
    "Glory is fleeting, but obscurity is forever. — Napoleon Bonaparte",
    "Power is not revealed by striking hard or often, but by striking true. — Honore de Balzac",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. — Ralph Waldo Emerson",
    "The more you sweat in peace, the less you bleed in war. — Norman Schwarzkopf",
    "The future depends on what you do today. — Mahatma Gandhi",
    "He who conquers himself is the mightiest warrior. — Confucius",
    "He who knows others is wise; he who knows himself is enlightened. — Lao Tzu",
    "Do not pray for an easy life, pray for the strength to endure a difficult one. — Bruce Lee",
    "Success is how high you bounce when you hit bottom. — George S. Patton",
    "The best way to gain a good reputation is to endeavor to be what you desire to appear. — Socrates",
    "A warrior is worthless unless he rises above others and stands strong in the midst of a storm. — Yamamoto Tsunetomo",
    "The soul becomes dyed with the color of its thoughts. — Marcus Aurelius",
    "In the midst of chaos, there is also opportunity. — Sun Tzu",
    "Fortune and love favor the brave. — Ovid",
    "Do what you can, with what you have, where you are. — Theodore Roosevelt",
    "Courage, above all things, is the first quality of a warrior. — Carl von Clausewitz"
]
